#!/bin/sh

set -e

PREREQ=""

prereqs()
{
	echo "${PREREQ}"
}

case "${1}" in
	prereqs)
		prereqs
		exit 0
		;;
esac

echo "dm-cache-ramdisk: Starting..."

# Calculate 25% of total RAM in KB
TOTAL_RAM_KB=$(grep MemTotal /proc/meminfo | awk '{print $2}')
CACHE_SIZE_KB=$((TOTAL_RAM_KB / 4))

modprobe -r brd || true
modprobe brd rd_nr=1 rd_size=$CACHE_SIZE_KB

sleep 1

echo "Unmounting root"
umount /root

echo "Creating/registering backing device"
ROOT_DEV=$(readlink -f /dev/disk/by-label/cloudimg-rootfs)
make-bcache -B $ROOT_DEV
echo $ROOT_DEV > /sys/fs/bcache/register
lsblk -f

echo "Creating/registering cache device"
make-bcache -C /dev/ram0
echo /dev/ram0 > /sys/fs/bcache/register
cset_uuid=$(bcache-super-show /dev/ram0 | awk -F'[[:space:]]+' 'tolower($1)=="cset.uuid"{print $NF}')

echo "Attaching cache $cset_uuid"
echo $cset_uuid > /sys/block/bcache0/bcache/attach

echo "Setting writeback mode"
echo writeback > /sys/block/bcache0/bcache/cache_mode

echo "Mounting root"
mount /dev/bcache0 "${rootmnt?}"
